// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/08/2025, 15:48:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/plugins/**/*.{js,ts,mjs}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/composables/**/*.{js,ts,mjs}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/utils/**/*.{js,ts,mjs}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/kirap/OneDrive/Área de Trabalho/aika-nakamura-portfolio/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;